#! /bin/sh
bspc monitor -d 1 2 3 4 5 6

bspc config border_width        4
bspc config window_gap          8
bspc config split_ratio         0.52
bspc config borderless_monocle  false
bspc config gapless_monocle     false

. ~/.config/bspwm/colors

bspc config top_padding 14px
bspc config normal_border_color "#$BSPWM_BORDERCOLOR_UNFOCUSED"
bspc config focused_border_color "#$BSPWM_BORDERCOLOR_FOCUSED"
bspc config focus_follows_pointer true


bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2 floating=on
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# silent bell
/usr/bin/xset b off

# keyboard settings
~/dotfiles/autostart.sh &

# start dropbox
dropbox start &

# start compton (shadows)
compton --config ~/.config/compton/compton.conf &

# start barpannel
~/.config/bspwm/panel &

# set background image
hsetroot -fill ~/Pictures/bg

# disable ctrl-s freeze
stty -ixon
