#!/bin/sh
mydir="$(dirname $0)"
. $mydir/panel_fifo
. $mydir/colors

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# for desktop in $(bspc query -D); do
#   bspc config -d $desktop border_width 1;
# done

bspc config border_width        1
bspc config window_gap          15
bspc config split_ratio         0.50
bspc config borderless_monocle  false
bspc config gapless_monocle     false
bspc config top_padding 15px
bspc config bottom_padding 5px
bspc config left_padding 5px
bspc config right_padding 5px
bspc config normal_border_color "#$C_BG"
bspc config focused_border_color "#$C_CYAN"
bspc config presel_border_color "#$C_YELLOW"
bspc config focus_follows_pointer true


bspc rule -a mplayer2 floating=on

# start barpannel
~/.config/bspwm/panel &
stalonetray &
