#! /bin/sh

bspc monitor -d 1 2 3 4 5 6

bspc config border_width        2
bspc config window_gap          4
bspc config split_ratio         0.52
bspc config borderless_monocle  false
bspc config gapless_monocle     false

bspc config top_padding 17px
bspc config normal_border_color "#2c3e50"
bspc config focused_border_color "#3498db"
bspc config focus_follows_pointer true


bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

~/dotfiles/autostart.sh &
~/.config/bar/barpannel &
hsetroot -fill ~/Pictures/bg.jpg
