#! /bin/sh
export PANEL_FIFO=/tmp/panel-fifo

if [ $(pgrep -cx pannel) -gt 1 ] ; then
printf "%s\n" "The panel is already running." >&2
exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

# workspaces (W)
bspc control --subscribe > "$PANEL_FIFO" &

# ram usage (R)
#free -m -s 2 | awk '/-/ {print "R" $3}' > "$PANEL_FIFO" &

# date and time (T)
clock -sf 'T%a, %d.%m.%y, %H:%M ' > "$PANEL_FIFO" &

# battery
battery -sf 'B%s %i' > "$PANEL_FIFO" || echo 'BCharging 100' > "$PANEL_FIFO" &

# current window title (A)
xtitle -sf 'A%s' > "$PANEL_FIFO" &

# volume (V)
while true; do
  printf "V%s\n" $(amixer | if grep -q "off"; then echo "mute"; else echo $(amixer | awk '/Front Left: Playback/ {print $5}' | sed 's/\[//g;s/\]//g');fi) > "$PANEL_FIFO"
  sleep 0.5s;
done &


. ~/.config/bspwm/colors

# start bar with input from fifo piped through panel_bar and then start stalonetray
cat "$PANEL_FIFO" | ~/.config/bspwm/panel_bar | bar -g x16+0+0 -F "#$OPACITY$COLOR_FOREGROUND" -B "#$OPACITYBAR$COLOR_BACKGROUND" -f "-*-tamsyn-medium-*-*--13-*-*-*-*-*-*-1,-misc-stlarch-medium-r-normal--10-100-75-75-c-80-iso10646-1" & stalonetray -i 16 -t false -bg "#$COLOR_BACKGROUND" --icon-gravity NE --geometry 20x1-280+0 --max-geometry 30x1-0-0 --kludges force_icons_size &

wait

