#!/bin/bash

# Add to your script before any calls to wmctrl.
export DISPLAY=:0

ACTIVEWORKSPACE=$(xdotool get_desktop);
ACTIVEWINDOW=$(printf 0x%08x $(xdotool getactivewindow));
case $1 in
    x)
      RESIZEX=true;
    ;;
    y)
      RESIZEX=false;
    ;;
esac;
WINDOWPROPS=$(wmctrl -G -l | sed -e '/^'$ACTIVEWINDOW'/!d');
X=$(echo $WINDOWPROPS | awk '{print $3}');
Y=$(echo $WINDOWPROPS | awk '{print $4}');
W=$(echo $WINDOWPROPS | awk '{print $5}');
H=$(echo $WINDOWPROPS | awk '{print $6}');
if $RESIZEX; then
  X=$(expr $X $2 $3);
else
  Y=$(expr $Y $2 $3);
fi;
wmctrl -i -r $ACTIVEWINDOW -e 0,$X,$Y,$W,$H
