#! /bin/bash

ACTIVEWORKSPACE=$(xdotool get_desktop)
ACTIVEWINDOW=$(printf 0x%08x $(xdotool getactivewindow))

ORDERCOLUMN=''
ORDERDIRECTION=''

case $1 in
    h|a|east|left)
      ORDERCOLUMN=2
      ORDERDIRECTION='-r'
    ;;
    j|s|south|down)
      ORDERCOLUMN=2
      ORDERDIRECTION=''
    ;;
    k|w|north|up)
      ORDERCOLUMN=3
      ORDERDIRECTION='-r'
    ;;
    l|d|west|right)
      ORDERCOLUMN=2
      ORDERDIRECTION=''
    ;;
esac

wmctrl -i -a \
$(wmctrl -G -l | sed -r 's/(0x[a-f0-9]+) +([0-9]+) +([0-9]+) +([0-9]+) +([0-9]+) +([0-9]+) +(.*)/\2 \3 \4 \5 \6 \1 \7/g' |\
  sed -e '/^'$ACTIVEWORKSPACE'/!d' |\
  sort -n -k $ORDERCOLUMN $ORDERDIRECTION |\
  awk '{print $6}' |\
  sed "0,/$ACTIVEWINDOW/d" |\
  sed -n "1p")
