#! /bin/bash
mydir="$(dirname $0)"
. $mydir/panel_fifo

echo W$(
wmctrl -d | \
awk '{print $2$9}' ORS='@@@' | \
sed -e 's/@@@/:/g' | \
sed -e 's/-/f/g' | \
sed -e 's/*/a/g' \
) > $PANEL_FIFO;

exit 0
