#! /bin/bash
mydir="$(dirname $0)"
. $mydir/panel_colors

shutdown="%{B$C_RED}%{A:i3-nagbar -t warning -m 'Really shutdown?' -b 'Yes!' 'shutdown now':}%{A}%{B-}"

volumecontrol="%{A:pavucontrol -t 1:}%{A}"

while read -r line ; do
  case $line in
    S*)
      # clock output
      clock="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${line#?} %{B-}%{F-}"
      ;;
    # V*)
    #   # volume output
    #   volumecontrol="A:pavucontrol -t 1:"
    #   volume="%{$volumecontrol}${line#?}%{A}"
    #   ;;
    T*)
      # xtitle output
      title=" %{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG} ${line#?} %{B-}%{F-}"
      ;;
    W*)
      # bspwm internal state
      wm_infos="%{A4:i3-msg workspace prev;$mydir/i3out:}%{A5:i3-msg workspace next;$mydir/i3out:}"
      IFS=':'
      set -- ${line#?}
      while [ $# -gt 0 ] ; do
        item=$1
        name=${item#?}
        desktop_switch="A:i3-msg workspace $name;$mydir/i3out:"
        move_window="A3:i3-msg move container to workspace $name:"
        case $item in
          a*)
            # active desktop
            wm_infos="${wm_infos}%{U$C_MAIN}%{+u} ${name} %{-u}%{B-}%{F-}"
            ;;
          f*)
            # free desktop
            wm_infos="${wm_infos}%{$desktop_switch}%{$move_window} ${name} %{A}%{A}%{B-}%{F-}"
            ;;
        esac
        shift
      done
      wm_infos="${wm_infos}%{A}%{A}"
      ;;
  esac
  printf "%s\n" "%{l}${title}%{c}${wm_infos}%{r}${volumecontrol} ${clock}${shutdown}"
done
