#!/bin/bash

DARK="#FF252525"
LIGHT="#FF2ecc71"
WHITE="#FFBCBCBC"
RED="#FFFF0000"

workspace(){
	SPACE_NUM=$(bspc query -D -d);
		case "$SPACE_NUM" in
			"1")
				WORKSPACE="■ □ □ □ □ □";;
			"2")
				WORKSPACE="□ ■ □ □ □ □";;
			"3")
				WORKSPACE="□ □ ■ □ □ □";;
			"4")
				WORKSPACE="□ □ □ ■ □ □";;
			"5")
				WORKSPACE="□ □ □ □ ■ □";;
			"6")
				WORKSPACE="□ □ □ □ □ ■";;
		esac
	echo $WORKSPACE
}

chg(){
  CHARGENUM=$(acpi --battery | awk '{gsub(/,/, "");} {print $4}' | sed 's/%//')
  CHARGE=$CHARGENUM
  if [ $CHARGENUM -lt 20 ];
  then
    echo  %{F$RED}$CHARGE%{F$WHITE};
  else
    echo  $CHARGE
  fi
}

bat(){
	echo  $(acpi -a | if grep -q "on-line"; then echo ""; else echo "⭫ $(chg)%"; fi)
}

ram(){
	echo  $(free -m | awk '/-/ {print $3}')
}

dat(){
	echo  $(date "+%H:%M  %d.%m.%y")
}

vol(){
	echo  $(amixer | if grep -q "off"; then echo "mute"; else echo $(amixer | awk '/Front Left: Playback/ {print $5}' | sed 's/\[//g;s/\]//g');fi)
}

mus(){
	#echo  $(test -z "$(mpc current)" || mpc current -f %title%)
  echo mus
}

paws(){
	#echo  $(mpc | if grep -q "paused"; then echo "▮▮"; else echo "♫"; fi)
  echo paws
}

wintitle(){
  echo  $(xprop -id $(xprop -root 32x '\t$0' _NET_ACTIVE_WINDOW | cut -f 2) WM_CLASS | cut -c-60 | awk '{print $4}' | sed 's/"//g')
}

while :; do
	echo  "%{B$DARK} %{F$WHITE}$(mus) %{F$DARK}%{B$LIGHT}%{F}%{B}%{F$DARK}%{B$LIGHT} ❏ $(wintitle) %{B}%{F}%{F$LIGHT}%{B}%{c}%{B$DARK} %{F$WHITE}$(workspace) %{B}%{F}%{c}%{r}%{F$LIGHT}%{F}%{B$LIGHT}%{F$DARK} $(bat) ram $(ram) ♫ $(vol)% %{B}%{F}%{F$DARK}%{B$LIGHT}%{F}%{B}%{B$DARK}%{F$WHITE} ◷ $(dat) %{B}%{F}"
sleep 0
done
