#! /bin/sh
#
# Example panel for LemonBoy's bar

~/.config/bar/panel_colors

while read -r line ; do
	case $line in
		T*)
			# clock output
      clock="%{F$DARK}%{B$LIGHT}%{F}%{B}%{B$DARK}%{F$WHITE} ◷ ${line#?}%{B}%{F}"
			;;
		A*)
			# current Application
      title="%{F$DARK}%{B$LIGHT} ❏ ${line#?} %{B} %{F}%{F$LIGHT}%{B}"
			;;
		W*)
			# bspwm internal state
			wm_infos=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
        # $name to get workspace name
				name=${item#?}
				case $item in
					O*)
						# focused occupied desktop
            wm_infos="$wm_infos %{B$DARK}%{F$WHITE}%{+u}■%{-u}%{B}%{F}"
						;;
					F*)
						# focused free desktop
            wm_infos="$wm_infos %{B$DARK}%{F$WHITE}%{+u}□%{-u}%{B}%{F}"
						;;
					U*)
						# focused urgent desktop
            wm_infos="$wm_infos %{B$DARK}%{F$WHITE}%{+u}■#{-u}%{B}%{F}"
						;;
					o*)
						# occupied desktop
            wm_infos="$wm_infos %{B$DARK}%{F$WHITE}■%{B}%{F}"
						;;
					f*)
						# free desktop
            wm_infos="$wm_infos %{B$DARK}%{F$WHITE}□%{B}%{F}"
						;;
					u*)
						# urgent desktop
            wm_infos="$wm_infos %{B$DARK}%{F$WHITE}■%{B}%{F}"
						;;
					L*)
						# layout
						;;
				esac
				shift
			done
      wm_infos="$wm_infos "
			;;
	esac

	#%{B$DARK} %{F$WHITE}$(mus) %{F$DARK}%{B$LIGHT}%{F}%{B}
  #%{F$DARK}%{B$LIGHT} ❏ $(wintitle) %{B} %{F}%{F$LIGHT}%{B}
  #%{c}%{B$DARK} %{F$WHITE}$(workspace) %{B}%{F} %{c}
  #%{r}%{F$LIGHT}%{F}%{B$LIGHT}%{F$DARK} $(bat) ram $(ram) ♫ $(vol)% %{B}%{F}
  #%{F$DARK}%{B$LIGHT}%{F}%{B}%{B$DARK}%{F$WHITE} ◷ $(dat) %{B}%{F}

	printf "%s\n" "%{l}$title%{c}$wm_infos%{r}$clock"
done


